version: '3.3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - ${GLOBAL_NETWORK:-postgres}
    restart: unless-stopped

networks:
  application:
    driver: bridge

volumes:
  postgres: